name: Keep Auth Service Alive

on:
  schedule:
    - cron: "*/15 * * * *"  # Run every 15 minutes
  workflow_dispatch:        # Manual run option

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping the login form
        run: |
          RESPONSE=$(curl -s -o body.txt -w "%{http_code}" -X POST https://auth.agilabuscorp.me/authentication/login \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "employeeId=${{ secrets.AUTH_EMPLOYEE_ID }}" \
            --data-urlencode "password=${{ secrets.AUTH_PASSWORD }}")

          echo "Status Code: $RESPONSE"
          echo "Response body:"
          cat body.txt

          if [ "$RESPONSE" -ne 200 ]; then
            echo "Login failed or service down"
            exit 1
          fi
