name: Keep Auth Service Alive

on:
  schedule:
    - cron: "*/6 * * * *"  # Every 6 minutes (as close as GitHub allows)
  workflow_dispatch:        # Manual trigger option

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
      - name: Send login request
        run: |
          echo "Sending POST request to keep auth service awake..."

          RESPONSE=$(curl -s -o body.txt -w "%{http_code}" -X POST https://auth.agilabuscorp.me/api/auth/login \
            -H "Content-Type: application/json" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)" \
            -H "Origin: https://auth.agilabuscorp.me" \
            -H "Referer: https://auth.agilabuscorp.me/authentication/login" \
            -d "{\"employeeId\":\"${{ secrets.AUTH_USERNAME }}\",\"password\":\"${{ secrets.AUTH_PASSWORD }}\"}"

          echo "Status Code: $RESPONSE"
          echo "Response Body:"
          cat body.txt

          if [ "$RESPONSE" -ne 200 ]; then
            echo "❌ Login failed or service error"
            exit 1
          else
            echo "✅ Login successful"
          fi
